sources:
  alertmanager:
    type: http
    address: 0.0.0.0
    port: 9090
    path: /alerts
    max_body_size_bytes: 1048576

transforms:
  testvrl:
    type: remap
    inputs: ["alertmanager"]
    source: |
      .

sinks:
  api_output:
    type: http
    inputs: ["testvrl"]
    uri: "https://open.feishu.cn/open-apis/bot/v2/hook/fddc37b3-2882-4d8f-90f2-279d307505e5"
    template: file://./feishu.j2
    headers:
      Content-Type: "application/json"
    timeout_ms: 5000
    retry_attempts: 3
    retry_interval_ms: 1000

  debug_output:
    type: console
    inputs: ["testvrl"]
    encoding: text
    template: file://./feishu.j2