sources:
  enqueue:
    type: http
    port: 9090

transforms:
  testvrl:
    type: remap
    inputs: ["enqueue"]
    source: |
      if exists(.req.body) {
        . = merge!(., .req.body)
        del(.req.body)
      }
      .

  testreroute:
    type: route
    inputs: ["enqueue"]
    reroute_unmatched: true
    routes:
      resolved:
        source: .req.body.status == "resolved"

sinks:
  api_output:
    type: http
    inputs: ["testvrl"]
    uri: "https://open.feishu.cn/open-apis/bot/v2/hook/{{ boturl }}"
    template: file://./feishu.j2
    headers:
      Content-Type: "application/json"
    timeout_ms: 5000
    retry_attempts: 3
    retry_interval_ms: 1000

  debug_unmatched:
    type: console
    inputs: ["testreroute._unmatched"]
    encoding: json

  debug_output:
    type: console
    inputs: ["testreroute.resolved"]
    encoding: json